name: Manhunt
description: A manhunt plugin.
version: '0.1.3'
main: tk.thesenate.manhunt.Manhunt
api-version: '1.16'
commands:
  manhunt:
    description: Add or remove hunters, and start a manhunt game.
    permission: manhunt.manhunt
permissions:
  durver.*:
    description: Gives access to all Manhunt commands.
    children:
      durver.manhunt: true
  durver.manhunt:
    description: Gives access to manhunt command.
    default: op