name: Manhunt
description: A simple manhunt plugin.
version: '1.0'
main: tk.thesenate.manhunt.Manhunt
api-version: '1.15'
commands:
  manhunt:
    description: Add or remove hunters, and start a manhunt game.
    usage: >
      Usage is /manhunt <addHunter/removeHunter> <players>
      then /manhunt <start/stop>
      or /manhunt list
    permission: manhunt
permissions:
  manhunt.*:
    description: Gives access to all Manhunt commands.
    children:
      manhunt: true
  manhunt:
    description: Gives access to manhunt command.
    default: op